### ISSUE TITLE
thread implementation to control watchdogs (sw and hw)

### ISSUE THREAD

**Issue by mariobaldini** [floripasat/obdh#1]
- thread priority: highest 
- period: 100ms
- action: set a given GPIO to high for 10ms. (low otherwise).

**Comment by eldertramontin** [comment]
- thread priority: highest                                                          -> (configMAX_PRIORITIES - 1)
- period: 100ms                                                                       -> (vTaskDelayUntil)
- action: set a given GPIO to high for 10ms. (low otherwise). -> (GIO 5.4[led pin on OBDH board] toggle with vTaskDelay)

**Comment by mariobaldini** [comment]
Implemented. 

Yet to be tested.
